services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
  
  fast-app:
    build: 
      context: .
      dockerfile: dockerfile
    image: fast-app:latest
    container_name: fast-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - env
    